server:
  ##port: 8080
  port: 8090
  servlet:
    context-path: /account
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/account?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    timeout: 5000
    # Redis服务器地址
    host: localhost
    port: 6379
#    password: My@2021
    jedis:
      pool:
        max-active: 8
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
         # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  jpa:
    show-sql: true
common:
  token-exp: 3600
urls:
  anon:
    - /**/ignore/**
    - /**/static/**
    #swagger相关路径放开
    - /**/v2/**
    - /**/swagger-resources/**
    - /**/doc.html
    - /**/webjars/**
logging:
  level:
    org.springframework: info
    org.hibernate.SQL: debug
  config: classpath:config/log4j2.xml